### PR TITLE
[1.8.9] Automagically set mod version

### PR DESCRIPTION
**Pull request by iarspider**
A tiny change to let gradle set mod version in .java file to help mods like Version Checker not be confused.

### CODE REVIEW

**Comment by AlgorithmX2** [comment]
Whoops, I thought I had already done this.

**Comment by AlgorithmX2** [comment]
@iarspider ; Can you please accept https://cla-assistant.io/AlgorithmX2/FlatColoredBlocks?pullRequest=8

Just trying to get some formalities out of the way.

**Comment by iarspider** [comment]
@AlgorithmX2 Done.

**Comment by AlgorithmX2** [comment]
Thanks :+1:

**Pull request merged**
